meta:
  url:
  title:
  description:
  siteName:
  sns: ['twitter']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: bullets # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    languages:
      - javascript
      - html
    plugins: []
    theme: tomorrow # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
